const questoesExemplo = [
  {
    question: "Qual anime é esse?",
    emoji: "🐉 ⚔️",
    options: ["Dragon Ball", "Naruto", "One Piece", "Bleach"],
    answer: "Dragon Ball",
  },
  {
    question: "Que anime é esse?",
    emoji: "🏴‍☠️ 🗺️",
    options: ["One Piece", "Demon Slayer", "Sword Art Online", "Jujutsu Kaisen"],
    answer: "One Piece",
  },
  {
    question: "Qual anime tem esse símbolo?",
    emoji: "🍥 🌙",
    options: ["Naruto", "Fullmetal Alchemist", "Bleach", "Code Geass"],
    answer: "Naruto",
  },
  {
    question: "Qual anime é esse?",
    emoji: "🦸‍♂️ 🏫",
    options: ["My Hero Academia", "Tokyo Ghoul", "Black Clover", "Akame ga Kill"],
    answer: "My Hero Academia",
  },
  {
    question: "Que anime é esse?",
    emoji: "👾 🔥",
    options: ["Pokemon", "Digimon", "Yu-Gi-Oh", "Beyblade"],
    answer: "Pokemon",
  },
  {
    question: "Qual anime tem esse visual?",
    emoji: "🩸 🕯️",
    options: ["Tokyo Ghoul", "Death Note", "Berserk", "Junji Ito Collection"],
    answer: "Tokyo Ghoul",
  },
  {
    question: "Qual anime é esse?",
    emoji: "🥋 🐼",
    options: ["One Punch Man", "Dragon Ball", "Samurai Champloo", "Tekken"],
    answer: "Dragon Ball",
  },
  {
    question: "Que anime é esse?",
    emoji: "🧑‍🚀 🌌",
    options: ["Cowboy Bebop", "Neon Genesis Evangelion", "Gurren Lagann", "Star Wars"],
    answer: "Cowboy Bebop",
  },
  {
    question: "Qual anime é esse?",
    emoji: "🧙‍♂️ ✨",
    options: ["Fairy Tail", "Black Clover", "Fullmetal Alchemist", "Demon Slayer"],
    answer: "Fairy Tail",
  },
  {
    question: "Que anime é esse?",
    emoji: "🎯 🏀",
    options: ["Haikyuu!!", "Blue Lock", "Slam Dunk", "Kuroko no Basket"],
    answer: "Haikyuu!!",
  },
  {
    question: "Qual anime é esse?",
    emoji: "🕯️🔥🌀💀",
    options: ["Junji Ito Collection", "Berserk", "Parasyte", "Death Note"],
    answer: "Junji Ito Collection",
  },
  {
    question: "Que anime é esse?",
    emoji: "🦊 🔥",
    options: ["Demon Slayer", "Fire Force", "Attack on Titan", "Mushishi"],
    answer: "Fire Force",
  },
  {
    question: "Qual anime tem um protagonista chamado Light?",
    emoji: "📘 🧠",
    options: ["Death Note", "Erased", "Steins;Gate", "Monster"],
    answer: "Death Note",
  },
  {
    question: "Qual anime se passa em um mundo de colheita e titãs?",
    emoji: "🧱 🆙",
    options: ["Attack on Titan", "Vinland Saga", "Jujutsu Kaisen", "Blue Period"],
    answer: "Attack on Titan",
  },
  {
    question: "Que anime é esse?",
    emoji: "🧪 ⚛️",
    options: ["Steins;Gate", "Mob Psycho 100", "Code Geass", "Boku no Hero"],
    answer: "Steins;Gate",
  },
  {
    question: "Qual anime tem esse estilo de luta e treinamento em escola?",
    emoji: "⚔️ 🎓",
    options: ["Jujutsu Kaisen", "My Hero Academia", "Blue Lock", "The Rising of the Shield Hero"],
    answer: "Jujutsu Kaisen",
  },
  {
    question: "Que anime é esse?",
    emoji: "🧭 🧨",
    options: ["Code Geass", "Psycho Pass", "Parasyte", "Fate/Zero"],
    answer: "Code Geass",
  },
  {
    question: "Qual anime representa uma luta por uma taça de futebol?",
    emoji: "⚽ 🏆",
    options: ["Blue Lock", "Inazuma Eleven", "Captain Tsubasa", "Kuroko no Basket"],
    answer: "Blue Lock",
  },
  {
    question: "Que anime é esse?",
    emoji: "🪄 🌙",
    options: ["Black Clover", "Fairy Tail", "Bleach", "Magi"],
    answer: "Black Clover",
  },
  {
    question: "Qual anime tem um personagem que usa uma arma de fogo com sensor de mente?",
    emoji: "🧠 🔫",
    options: ["Psycho-Pass", "Toradora!", "Angel Beats", "A Silent Voice"],
    answer: "Psycho-Pass",
  },
  {
    question: "Que anime é esse?",
    emoji: "🤍 🩸",
    options: ["Chainsaw Man", "Berserk", "Parasyte", "Dorohedoro"],
    answer: "Chainsaw Man",
  },
  {
    question: "Qual anime tem esse clima de mistério e assassinato?",
    emoji: "🕵️ 🧩",
    options: ["Monster", "Death Parade", "Erased", "Moriarty the Patriot"],
    answer: "Monster",
  },
  {
    question: "Qual anime é esse?",
    emoji: "💀 🧪",
    options: ["Parasyte", "Hellsing", "Berserk", "Devilman Crybaby"],
    answer: "Parasyte",
  },
  {
    question: "Que anime é esse?",
    emoji: "🩹 🧠",
    options: ["Mob Psycho 100", "Your Name", "A Silent Voice", "Odd Taxi"],
    answer: "Mob Psycho 100",
  },
  {
    question: "Qual anime tem como tema a guerra de ciclos e reencarnação?",
    emoji: "🔁 ⚔️",
    options: ["Re:Zero", "Vinland Saga", "Shouwa Genroku Rakugo Shinjuu", "The Promised Neverland"],
    answer: "Re:Zero",
  },
  {
    question: "Que anime é esse?",
    emoji: "🧠 🕳️",
    options: ["Made in Abyss", "Erased", "No Game No Life", "Mushishi"],
    answer: "Made in Abyss",
  },
  {
    question: "Qual anime é conhecido por ter um protagonista que vive em um mundo de ruínas e mistério?",
    emoji: "🏚️ 🧭",
    options: ["Berserk", "Mushishi", "The Promised Neverland", "The Ancient Magus' Bride"],
    answer: "Berserk",
  },
  {
    question: "Que anime é esse?",
    emoji: "🖤 🧨",
    options: ["Devilman Crybaby", "Blue Exorcist", "Soul Eater", "Trigun"],
    answer: "Devilman Crybaby",
  },
  {
    question: "Qual anime apresenta um mundo regido por uma cidade subordinada aos mortos?",
    emoji: "💀 🏙️",
    options: ["Death Parade", "Hellsing Ultimate", "Yona of the Dawn", "Baccano"],
    answer: "Death Parade",
  },
  {
    question: "Que anime é esse?",
    emoji: "🧩 🕰️",
    options: ["Steins;Gate", "The Melancholy of Haruhi Suzumiya", "Dr. Stone", "Kaiba"],
    answer: "Steins;Gate",
  },
  {
    question: "Qual anime tem esse clima de sobrevivência em um ambiente extremo?",
    emoji: "❄️ 🏕️",
    options: ["Dr. Stone", "The Promised Neverland", "FreakAngels", "The Boy and the Beast"],
    answer: "Dr. Stone",
  },
  {
    question: "Que anime é esse?",
    emoji: "🩸 🐍",
    options: ["Berserk", "Vinland Saga", "Claymore", "Rurouni Kenshin"],
    answer: "Berserk",
  },
  {
    question: "Qual anime tem essa vibe de horror psicológico e literatura de terror?",
    emoji: "🕯️🔥🌀💀",
    options: ["Junji Ito Collection", "The Witcher", "KonoSuba", "Rascal Does Not Dream"],
    answer: "Junji Ito Collection",
  },
  {
    question: "Que anime é esse?",
    emoji: "🏯 🌊",
    options: ["Samurai Champloo", "Vinland Saga", "Rurouni Kenshin", "Dororo"],
    answer: "Vinland Saga",
  },
  {
    question: "Qual anime é conhecido por ter um enredo sobre confiança, manipulação e política?",
    emoji: "🎭 👑",
    options: ["Moriarty the Patriot", "Psycho-Pass", "House of Five Leaves", "Nier: Automata"],
    answer: "Moriarty the Patriot",
  },
  {
    question: "Que anime é esse?",
    emoji: "🧬 ⚙️",
    options: ["Serial Experiments Lain", "The Disastrous Life of Saiki K.", "Kizumonogatari", "Natsume's Book of Friends"],
    answer: "Serial Experiments Lain",
  },
];

export default questoesExemplo;
